name: Discord_Link
version: @version@
author: ShinyAfro
description: Discord-Link Bungee module for proxy-level command processing.
main: net.dirtcraft.discord.discordlink.DiscordLink
api-version: 1.13
depend: [LiteBans]